####### 注册中心 ##########

## server (eureka 默认端口为：8761)
server:
  port: 9999

eureka:
  instance:
    hostname: localhost
  client:
    # 是否注册到eureka
    register-with-eureka: false
    # 是否从eureka获取注册信息
    fetch-registry: false
    # eureka服务器的地址（注意：地址最后面的 /eureka/ 这个是固定值）
    service-url: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    ##我保护模式关闭
    enable-self-preservation: false
    #设置清理无效节点的时间间隔，默认60000，即是60s
    eviction-interval-timer-in-ms: 10000



spring:
  cloud:
    config:
      uri: http://localhost:8888/casconfigserver
  security:
    user:
      name: admin
      password: admin
  application:
    name: eureka
